import http.client,http.server,importlib.util,json,tempfile,threading
from pathlib import Path
ROOT=Path(r"D:/LAN-Share/lora/_work/comfy_panel");spec=importlib.util.spec_from_file_location('retro_http',ROOT/'server.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
root=Path(tempfile.mkdtemp());m.DATA_DIR=root;m.JOBS_DIR=root/'jobs';m.JOBS_DIR.mkdir();m.JOBS_FILE=root/'jobs.json';m.FAVORITES_DIR=root/'favorites';m.FAVORITES_DIR.mkdir();m.FAVORITES_FILE=root/'favorites.json';m._jobs={};m._favorites={};m.run_job=lambda job:None
srv=m.BoundedHTTPServer(('127.0.0.1',0),m.Handler);threading.Thread(target=srv.serve_forever,daemon=True).start()
payload={'workflow':'anima02','prompt':'adult woman, fashion portrait','negative_prompt':'text, watermark','prompt_mode':'manual','width':768,'height':1024,'batch':1,'hd':0,'seed':321,'seed_mode':'fixed','style_id':'retro_manga_luxury','style_variant':'default','mode':'original','generation_backend':'cloud','client_request_id':'retro-trusted','loras':{'LORA1':'attacker.safetensors'},'trigger':'attacker','lora_strengths':{'LORA1':99}}
try:
 c=http.client.HTTPConnection('127.0.0.1',srv.server_port,timeout=10);raw=json.dumps(payload).encode();c.request('POST','/api/generate',raw,{'Content-Type':'application/json'});r=c.getresponse();data=json.loads(r.read());status=r.status;c.close();assert status==200,(status,data);job=m._jobs[data['job_id']];assert job['loras']=={'LORA1':'09_style321_v1_step200.safetensors','LORA2':'09_style321_v1_step200.safetensors'};assert job['lora_strengths']=={'LORA1':0.4,'LORA2':0.0};assert job['trigger']=='jt_style321_v1';assert job['style_id']=='retro_manga_luxury';print('RETRO_STYLE_HTTP_OK',{'status':status,'loras':job['loras'],'strengths':job['lora_strengths'],'trigger':job['trigger']})
finally:srv.shutdown();srv.server_close()
