const api=async(path,opt={})=>{const r=await fetch(path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d};
let WFS=[],cur=null,mediaFiles={},genRunning=false;const pendingVideoSubmitKey='jt-pending-video-submit';
async function init(){const a=await api('/api/workflows');WFS=a.filter(w=>w.kind==='video');const box=document.getElementById('wfSwitch');box.innerHTML='';WFS.forEach(w=>{const b=document.createElement('button');b.dataset.wf=w.id;b.innerHTML='<b>'+w.name+'</b>';b.onclick=()=>{cur=w;renderForm();renderSwitch()};box.appendChild(b)});if(WFS.length)cur=WFS[0];renderForm();renderSwitch()}
function renderSwitch(){document.querySelectorAll('#wfSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.wf===cur.id))}
function isVideoType(t){return t==='video'}
function renderForm(){const f=document.getElementById('wfForm');f.innerHTML='<div class="note"><b>'+cur.name+'</b><br>'+cur.desc+'</div>';
  const media=Object.entries(cur.rh_media||{});
  media.forEach(([key,m])=>{const lab=document.createElement('label');lab.textContent=m.label+(m.required?'（必传）':'（可选）');f.appendChild(lab);
    const drop=document.createElement('div');drop.className='drop';drop.innerHTML='<span>点击选择或拖入文件</span><div class="fn"></div>';drop.onclick=()=>{const inp=document.createElement('input');inp.type='file';inp.accept=isVideoType(m.type)?'video/*':'image/*';inp.onchange=()=>{if(inp.files[0])uploadMedia(key,m,inp.files[0],drop)};inp.click()};
    f.appendChild(drop)});
  const params=Object.entries(cur.rh_params||{});
  params.forEach(([key,p])=>{if(key==='prompt'||key==='negative'){const lab=document.createElement('label');lab.textContent=p.label+(key==='prompt'?'（必填）':'');f.appendChild(lab);const ta=document.createElement('textarea');ta.id='param_'+key;if(cur.prompt_placeholder&&key==='prompt')ta.placeholder=cur.prompt_placeholder;if(key==='prompt'&&cur.prompt_hint){const h=document.createElement('div');h.className='note';h.style.color='#c26a4a';h.textContent=cur.prompt_hint;f.appendChild(h)}f.appendChild(ta);return}
    const lab=document.createElement('label');lab.textContent=p.label;f.appendChild(lab);
    if(p.type==='number'){const inp=document.createElement('input');inp.type='number';inp.id='param_'+key;const d=(cur.params_defaults||{})[key];if(d!==undefined)inp.value=d;f.appendChild(inp)}
    else{const inp=document.createElement('input');inp.type='text';inp.id='param_'+key;const d=(cur.params_defaults||{})[key];if(d!==undefined)inp.value=d;f.appendChild(inp)}})}
async function uploadMedia(key,m,file,drop){const fnEl=drop.querySelector('.fn');fnEl.textContent='上传中…';try{const buf=await file.arrayBuffer();const b64=await blobToB64(new Blob([buf]));const r=await api('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({filename:file.name,data:b64})});mediaFiles[key]=r.fileName;fnEl.textContent='✓ '+file.name+' → '+r.fileName.slice(0,24)+'…';drop.style.borderColor='#8fbf9f'}catch(e){fnEl.textContent='✗ 上传失败：'+e.message;mediaFiles[key]=undefined}}
function blobToB64(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]);fr.onerror=rej;fr.readAsDataURL(blob)})}
function collectParams(){const p={};Object.keys(cur.rh_params||{}).forEach(k=>{const el=document.getElementById('param_'+k);if(el&&el.value!=='')p[k]=el.value});return p}
function addResult(j,container){container.innerHTML='';(j.images||[]).forEach((im,i)=>{const w=document.createElement('div');w.className='job';const isVid=/\.(mp4|mov|webm|avi|mkv)(\?|$)/i.test(im.url);w.innerHTML='<div class="note">种子：'+(j.seed??j.sequence_seed??'未知')+' · '+im.file+'</div>'+(isVid?'<video src="'+im.url+'" controls></video>':'<img src="'+(im.preview_url||im.url)+'">')+'<button class="dl fav">♥ 收藏此结果</button><a class="dl" target="_blank" href="'+im.url+'">⬇ 下载原文件</a>';w.querySelector('.fav').onclick=async e=>{e.target.disabled=true;e.target.textContent='收藏中…';try{await api('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:j.id,image_index:i})});e.target.textContent='✓ 已收藏'}catch(x){e.target.disabled=false;e.target.textContent='收藏失败：'+x.message}};container.appendChild(w)})}
const tasks=new Map(); // job_id -> {card, timeEl, metaEl, spinEl, timer, startTs, wfName}
function fmtTime(s){s=Math.floor(s);const m=String(Math.floor(s/60)).padStart(2,'0'),ss=String(s%60).padStart(2,'0');return m+':'+ss}
function refreshTaskCount(){const n=tasks.size;document.getElementById('taskCount').textContent=n+' 个任务（最多3个并发）'}
function taskStatusText(j){const s=j.provider_status||j.status;if(j.status==='done')return '✓ 完成';if(j.status==='error')return '✗ 失败';if(s==='SUBMITTING')return '排队中…';if(s==='RUNNING')return '生成中…';return s||'处理中…'}
function videoCoinText(j){if(j.rh_coins!==null&&j.rh_coins!==undefined&&j.rh_coins!=='')return'RH币：'+String(j.rh_coins);return(j.status==='done'||j.status==='error')?'RH币：未返回':'RH币：统计中'}
function taskStatusClass(j){if(j.status==='done')return 'done';if(j.status==='error')return 'err';return ''}
function addTaskCard(jobId,wfName){if(tasks.has(jobId))return;const list=document.getElementById('taskList');const card=document.createElement('div');card.className='task-card';card.innerHTML='<div class="task-spin"></div><div class="task-info"><div class="task-name">'+wfName+'</div><div class="task-meta" id="meta_'+jobId+'">排队中…</div></div><div class="task-time" id="time_'+jobId+'">00:00</div><div class="task-result" id="res_'+jobId+'"></div>';list.prepend(card);const t={card,timeEl:card.querySelector('#time_'+jobId),metaEl:card.querySelector('#meta_'+jobId),spinEl:card.querySelector('.task-spin'),resEl:card.querySelector('#res_'+jobId),timer:null,startTs:Date.now(),wfName};tasks.set(jobId,t);t.timer=setInterval(()=>{t.timeEl.textContent=fmtTime((Date.now()-t.startTs)/1000)},500);refreshTaskCount()}
function removeTaskCard(jobId){const t=tasks.get(jobId);if(!t)return;if(t.timer)clearInterval(t.timer);t.card.remove();tasks.delete(jobId);refreshTaskCount()}
function renderTaskResult(j,resEl){resEl.innerHTML='';(j.images||[]).forEach((im,i)=>{const isVid=/\.(mp4|mov|webm|avi|mkv)(\?|$)/i.test(im.url);const w=document.createElement('div');w.innerHTML=(isVid?'<video src="'+im.url+'" controls></video>':'<img src="'+(im.preview_url||im.url)+'">')+'<a class="dl" target="_blank" href="'+im.url+'">⬇ 下载原文件</a>';resEl.appendChild(w)})}
function pollTask(jobId){const t=tasks.get(jobId);if(!t)return;api('/api/job/'+jobId).then(j=>{if(!tasks.has(jobId))return;t.metaEl.textContent=taskStatusText(j)+' · '+videoCoinText(j);t.spinEl.className='task-spin '+taskStatusClass(j);if(j.status==='done'){if(t.timer){clearInterval(t.timer);t.timer=null}t.timeEl.textContent=fmtTime(j.elapsed||0);renderTaskResult(j,t.resEl);if(j.images&&j.images.length){const im=j.images[0];const fav=document.createElement('button');fav.className='dl';fav.textContent='♥ 收藏此结果';fav.onclick=async e=>{e.target.disabled=true;e.target.textContent='收藏中…';try{await api('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:jobId,image_index:0})});e.target.textContent='✓ 已收藏'}catch(x){e.target.disabled=false;e.target.textContent='收藏失败：'+x.message}};t.resEl.appendChild(fav)}}else if(j.status==='error'){if(t.timer){clearInterval(t.timer);t.timer=null}t.timeEl.textContent='—';t.metaEl.textContent='✗ '+(j.error||'生成失败');setTimeout(()=>removeTaskCard(jobId),8000)}else{setTimeout(()=>pollTask(jobId),5000)}}).catch(()=>{setTimeout(()=>pollTask(jobId),8000)})}
async function generate(){if(genRunning)return;if(!cur)return;genRunning=true;const btn=document.getElementById('genBtn');btn.disabled=true;const st=document.getElementById('genStatus');st.textContent='正在提交…';document.getElementById('genResult').innerHTML='';let pending={};try{pending=JSON.parse(localStorage.getItem(pendingVideoSubmitKey)||'{}')}catch{}const client_request_id=pending.workflow===cur.id&&pending.id?pending.id:'video-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(pendingVideoSubmitKey,JSON.stringify({workflow:cur.id,id:client_request_id}));try{const prompt=(document.getElementById('param_prompt')?.value||'').trim();if(!prompt)throw new Error('提示词不能为空');const required=Object.entries(cur.rh_media||{}).filter(([,m])=>m.required).map(([k])=>k);const missing=required.filter(k=>!mediaFiles[k]);if(missing.length)throw new Error('缺少必传素材：'+missing.join(', '));const body={workflow:cur.id,prompt:prompt,negative_prompt:(document.getElementById('param_negative')?.value||'').trim(),media:mediaFiles,params:collectParams(),client_request_id};const r=await api('/api/video-generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});localStorage.removeItem(pendingVideoSubmitKey);if(!r.job_id)throw new Error(r.error||'提交失败');addTaskCard(r.job_id,cur.name);st.textContent='✓ 已提交，任务 '+r.job_id+' 在下方队列中';pollTask(r.job_id)}catch(e){st.textContent='✗ '+e.message+'；网络不明时再次点击会复用请求号'}finally{genRunning=false;btn.disabled=false}}
async function history(){const l=document.getElementById('histList');l.textContent='加载中…';const a=await api('/api/jobs?scope=video');l.replaceChildren();a.filter(j=>j.workflow&&WFS.find(w=>w.id===j.workflow)).slice(0,10).forEach(j=>{const w=WFS.find(x=>x.id===j.workflow),d=document.createElement('div'),title=document.createElement('b'),note=document.createElement('div'),button=document.createElement('button');d.className='job';title.textContent=w?w.name:'视频';note.className='note';note.textContent=j.status+' · '+videoCoinText(j)+' · '+(j.elapsed||'')+'秒';button.className='dl';button.textContent='查看结果';button.onclick=()=>addResult(j,d);d.append(title,note,button);l.appendChild(d)})}
async function favorites(){const l=document.getElementById('favList');l.textContent='加载中…';const a=await api('/api/favorites');l.textContent='';a.forEach(f=>{const d=document.createElement('div');d.className='job';const promptNode=document.createElement('div');promptNode.className='note';promptNode.textContent=(f.prompt||'').slice(0,120);const img=document.createElement('img');img.src=f.preview_url||f.image_url;const link=document.createElement('a');link.className='dl';link.href=f.image_url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='⬇ 下载';d.append(promptNode,img,link);l.appendChild(d)})}
document.getElementById('genBtn').onclick=generate;document.getElementById('histOpen').onclick=()=>{histOverlay.classList.add('open');history()};document.getElementById('favOpen').onclick=()=>{favOverlay.classList.add('open');favorites()};document.querySelectorAll('.overlay .close').forEach(b=>b.onclick=()=>b.closest('.overlay').classList.remove('open'));init();
