const api=async(path,opt={})=>{const r=await fetch(path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok){const error=new Error(d.error||('HTTP '+r.status));error.data=d;error.status=r.status;throw error}return d};
let WFS=[],cur=null,genRunning=false,renderVersion=0;const pendingVideoSubmitKey='jt-pending-video-submit',mediaStateByWorkflow=new Map();
function ensureMediaState(workflowId){if(!mediaStateByWorkflow.has(workflowId))mediaStateByWorkflow.set(workflowId,{tokens:{},names:{},uploadIds:{}});return mediaStateByWorkflow.get(workflowId)}
function selectVideoWorkflow(workflow){cur=workflow;renderVersion++;renderForm();renderSwitch()}
async function recoverTasks(){let a=[];try{a=await api('/api/jobs?scope=video')}catch{return}a.filter(j=>j&&(j.status==='running'||j.status==='recovering')).forEach(j=>{const jobId=String(j.id||'');if(!jobId||tasks.has(jobId))return;const wf=WFS.find(w=>w.id===j.workflow),wfName=(wf&&wf.name)||j.wf_name||'视频任务';addTaskCard(jobId,wfName);pollTask(jobId)})}
async function init(){const box=document.getElementById('wfSwitch'),form=document.getElementById('wfForm'),btn=document.getElementById('genBtn');box.innerHTML='<div class="config-loading">正在加载视频工作流…</div>';form.innerHTML='<div class="config-loading">加载完成后可设置提示词和素材</div>';btn.disabled=true;try{const a=await api('/api/workflows');WFS=a.filter(w=>w.kind==='video');if(!WFS.length)throw new Error('没有可用的视频工作流');box.replaceChildren();const grouped={};WFS.forEach(w=>(grouped[w.section||'其他']??=[]).push(w));Object.entries(grouped).forEach(([section,items])=>{const group=document.createElement('div'),heading=document.createElement('div');group.className='workflow-section';heading.className='workflow-section-title';heading.textContent=section;group.appendChild(heading);items.forEach(w=>{const b=document.createElement('button'),name=document.createElement('b');b.type='button';b.dataset.wf=w.id;name.textContent=w.name;b.appendChild(name);b.onclick=()=>selectVideoWorkflow(w);group.appendChild(b)});box.appendChild(group)});selectVideoWorkflow(WFS[0]);btn.disabled=false}catch(e){cur=null;box.innerHTML='<div class="config-error"><b>视频配置加载失败</b><span></span><button type="button">重新加载</button></div>';box.querySelector('span').textContent=e.message;box.querySelector('button').onclick=retryWorkflows;form.innerHTML='<div class="config-error"><span>请确认服务连接后重试，现有任务和素材不会被提交。</span></div>'}}function retryWorkflows(){init()}
function renderSwitch(){document.querySelectorAll('#wfSwitch button').forEach(b=>b.classList.toggle('active',b.dataset.wf===cur.id))}
function isVideoType(t){return t==='video'}
function paramDefault(key,p){return Object.prototype.hasOwnProperty.call(p,'default')?p.default:(cur.params_defaults||{})[key]}
function optionValue(option){return typeof option==='object'?String(option.value??option.name??''):String(option)}
function optionLabel(option){return typeof option==='object'?String(option.label??option.name??option.value??''):String(option)}
function renderForm(){const f=document.getElementById('wfForm'),workflow=cur,version=renderVersion,state=ensureMediaState(workflow.id);f.replaceChildren();const intro=document.createElement('div'),title=document.createElement('b'),desc=document.createElement('span');intro.className='note';title.textContent=workflow.name;desc.textContent=workflow.desc;intro.append(title,document.createElement('br'),desc);f.appendChild(intro);
  const media=Object.entries(workflow.rh_media||{});
  media.forEach(([key,m])=>{const lab=document.createElement('label');lab.textContent=m.label+(m.required?'（必传）':'（可选）');f.appendChild(lab);
    const drop=document.createElement('div'),copy=document.createElement('span'),fn=document.createElement('div'),inp=document.createElement('input');drop.className='drop';drop.tabIndex=0;drop.setAttribute('role','button');drop.setAttribute('aria-label','选择或拖入'+String(m.label||'素材'));drop.dataset.mediaKey=key;copy.textContent='点击选择或拖入文件';fn.className='fn';fn.setAttribute('aria-live','polite');inp.type='file';inp.hidden=true;inp.accept=isVideoType(m.type)?'video/*':'image/*';drop.append(copy,fn,inp);if(state.tokens[key]){drop.classList.add('has-file');fn.textContent='✓ '+state.names[key]+' 已上传'}const accept=file=>{if(file)uploadMedia(key,m,file,drop,workflow,version,state)};drop.onclick=event=>{if(event.target!==inp)inp.click()};drop.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();inp.click()}};drop.ondragover=event=>{event.preventDefault();drop.classList.add('is-dragging')};drop.ondragleave=()=>drop.classList.remove('is-dragging');drop.ondrop=event=>{event.preventDefault();drop.classList.remove('is-dragging');accept(event.dataTransfer?.files?.[0])};inp.onchange=()=>accept(inp.files[0]);
    f.appendChild(drop)});
  const params=Object.entries(cur.rh_params||{});
  params.forEach(([key,p])=>{const lab=document.createElement('label');lab.textContent=p.label+(p.required?'（必填）':'');f.appendChild(lab);let inp;
    if(p.type==='text'||p.type==='textarea'||key==='prompt'||key==='negative'){inp=document.createElement('textarea');if(cur.prompt_placeholder&&key==='prompt')inp.placeholder=cur.prompt_placeholder;if(key==='prompt'&&cur.prompt_hint){const h=document.createElement('div');h.className='note';h.style.color='#c26a4a';h.textContent=cur.prompt_hint;f.appendChild(h)}}
    else if(p.type==='boolean'){inp=document.createElement('input');inp.type='checkbox'}
    else if(p.type==='select'){inp=document.createElement('select');(p.options||[]).forEach(option=>{const item=document.createElement('option');item.value=optionValue(option);item.textContent=optionLabel(option);inp.appendChild(item)})}
    else{inp=document.createElement('input');inp.type=(p.type==='number'||p.type==='int'||p.vtype==='int'||p.vtype==='float')?'number':'text';if(p.min!==undefined)inp.min=p.min;if(p.max!==undefined)inp.max=p.max;if(p.step!==undefined)inp.step=p.step;else if(p.type==='int'||p.vtype==='int')inp.step='1'}
    inp.id='param_'+key;inp.dataset.paramType=p.vtype||p.type||'text';const d=paramDefault(key,p);if(d!==undefined){if(inp.type==='checkbox')inp.checked=d===true;else inp.value=d}f.appendChild(inp)});
  (cur.fixed_features||[]).forEach(text=>{const note=document.createElement('div');note.className='note unavailable';note.textContent=text;f.appendChild(note)})}
async function uploadMedia(key,m,file,drop,workflow,version,state){const fnEl=drop.querySelector('.fn'),uploadId=(state.uploadIds[key]||0)+1;state.uploadIds[key]=uploadId;fnEl.textContent='上传中…';drop.classList.remove('has-file');try{const buf=await file.arrayBuffer();const b64=await blobToB64(new Blob([buf]));const r=await api('/api/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({workflow:workflow.id,input_key:key,filename:file.name,data:b64})});if(state.uploadIds[key]!==uploadId)return;state.tokens[key]=r.uploadToken;state.names[key]=file.name;const activeDrop=currentMediaDrop(workflow.id,key,version,drop);if(activeDrop){activeDrop.classList.add('has-file');activeDrop.querySelector('.fn').textContent='✓ '+file.name+' 已上传'}}catch(e){if(state.uploadIds[key]!==uploadId)return;delete state.tokens[key];delete state.names[key];const activeDrop=currentMediaDrop(workflow.id,key,version,drop);if(activeDrop){activeDrop.classList.remove('has-file');activeDrop.querySelector('.fn').textContent='✗ 上传失败：'+e.message}}}
function currentMediaDrop(workflowId,key,version,original){if(cur?.id!==workflowId)return null;if(version===renderVersion&&original.isConnected)return original;return Array.from(document.querySelectorAll('.drop')).find(item=>item.dataset.mediaKey===key)||null}
function blobToB64(blob){return new Promise((res,rej)=>{const fr=new FileReader();fr.onload=()=>res(String(fr.result).split(',')[1]);fr.onerror=rej;fr.readAsDataURL(blob)})}
function readParamValue(el){if(el.type==='checkbox')return el.checked;if(el.value==='')return'';if(el.dataset.paramType==='int')return Number.parseInt(el.value,10);if(el.dataset.paramType==='float'||el.dataset.paramType==='number')return Number(el.value);return el.value}
function collectParams(){const p={};Object.keys(cur.rh_params||{}).forEach(k=>{const el=document.getElementById('param_'+k);if(el){const value=readParamValue(el);if(value!=='')p[k]=value}});return p}
function safeMediaUrl(value){try{const u=new URL(String(value||''),location.origin);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:''}catch{return''}}
function hasRealSeed(j){const value=j?.params?.seed??j?.seed;return typeof value==='number'&&Number.isFinite(value)}
function seedSegment(j){const value=j?.params?.seed??j?.seed;return hasRealSeed(j)?('种子：'+value+' · '):''}
function resultMediaKind(im,url){const type=String(im.file_type||im.fileType||im.outputType||im.output_type||im.type||'').trim().toLowerCase().split(';')[0].replace(/^\./,''),path=new URL(url||location.origin).pathname;if(type==='application/zip'||type==='zip'||/\.zip$/i.test(path))return'file';if(type.startsWith('video/')||['video','mp4','mov','webm','avi','mkv'].includes(type)||/\.(mp4|mov|webm|avi|mkv)$/i.test(path))return'video';if(type.startsWith('image/')||['image','png','jpg','jpeg','webp','gif','avif'].includes(type)||/\.(png|jpe?g|webp|gif|avif)$/i.test(path))return'image';return'file'}
const galleryItems=[];let galleryIndex=-1;
function registerGalleryJob(j){(j.images||[]).forEach((im,i)=>{const key=j.id+':'+i;if(!galleryItems.some(x=>x.key===key))galleryItems.push({key,j,im,i})});if(galleryItems.length){galleryIndex=galleryItems.length-1;renderMediaGallery()}}
function selectGalleryItem(index){if(!galleryItems.length)return;galleryIndex=(index+galleryItems.length)%galleryItems.length;renderMediaGallery()}
function renderMediaGallery(){const main=document.getElementById('galleryMain'),thumbs=document.getElementById('galleryThumbs');if(!main||!thumbs||galleryIndex<0)return;main.replaceChildren();thumbs.replaceChildren();const item=galleryItems[galleryIndex],url=safeMediaUrl(item.im.url),preview=safeMediaUrl(item.im.preview_url),kind=resultMediaKind(item.im,url),note=document.createElement('div');note.className='gallery-meta';note.textContent=seedSegment(item.j)+String(item.im.stage_label||item.im.file||'结果');main.appendChild(note);if(kind==='file'){const file=document.createElement('div');file.className='file-result';file.textContent='结果文件已生成，可直接下载';main.appendChild(file)}else{const media=document.createElement(kind==='video'?'video':'img');media.src=kind==='video'?url:(preview||url);if(kind==='video')media.controls=true;main.appendChild(media)}const actions=document.createElement('div'),download=document.createElement('a'),favorite=document.createElement('button');actions.className='gallery-actions';download.className='dl';download.href=url;download.target='_blank';download.rel='noopener noreferrer';download.textContent=kind==='file'?'⬇ 下载结果文件':'⬇ 下载原文件';favorite.className='dl';favorite.textContent='♥ 收藏';favorite.disabled=kind==='file';favorite.onclick=async()=>{favorite.disabled=true;try{await api('/api/favorites',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({job_id:item.j.id,image_index:item.i})});favorite.textContent='✓ 已收藏'}catch(e){favorite.disabled=false;favorite.textContent='收藏失败：'+e.message}};actions.append(favorite,download);main.appendChild(actions);galleryItems.forEach((entry,index)=>{const b=document.createElement('button');b.className='gallery-thumb'+(index===galleryIndex?' active':'');b.type='button';b.onclick=()=>selectGalleryItem(index);const src=safeMediaUrl(entry.im.preview_url)||safeMediaUrl(entry.im.url);if(resultMediaKind(entry.im,src)==='image'){const img=document.createElement('img');img.src=src;b.appendChild(img)}else{const span=document.createElement('span');span.textContent=resultMediaKind(entry.im,src)==='video'?'▶':'ZIP';b.appendChild(span)}b.title=entry.j.wf_name||entry.j.workflow||'生成结果';thumbs.appendChild(b)});document.getElementById('galleryPrev').disabled=galleryItems.length<2;document.getElementById('galleryNext').disabled=galleryItems.length<2;document.getElementById('mediaGallery').hidden=false;document.getElementById('videoEmpty').classList.add('hidden')}
function addResult(j){registerGalleryJob(j)}
const tasks=new Map(); // job_id -> {card, timeEl, metaEl, spinEl, timer, startTs, wfName}
function fmtTime(s){s=Math.floor(s);const m=String(Math.floor(s/60)).padStart(2,'0'),ss=String(s%60).padStart(2,'0');return m+':'+ss}
function refreshTaskCount(){const n=tasks.size;document.getElementById('taskCount').textContent=n+' 个任务（最多2个并发）'}
function taskStatusText(j){const s=j.provider_status||j.status;if(j.status==='done')return '✓ 完成';if(j.status==='error')return '✗ 失败';if(s==='SUBMITTING')return '排队中…';if(s==='RUNNING')return '生成中…';return s||'处理中…'}
function videoCoinText(j){if(j.rh_coins!==null&&j.rh_coins!==undefined&&j.rh_coins!=='')return'RH币：'+String(j.rh_coins);return(j.status==='done'||j.status==='error')?'RH币：未返回':'RH币：统计中'}
function taskStatusClass(j){if(j.status==='done')return 'done';if(j.status==='error')return 'err';return ''}
function addTaskCard(jobId,wfName){if(tasks.has(jobId))return tasks.get(jobId);const list=document.getElementById('taskList'),card=document.createElement('div'),spin=document.createElement('div'),info=document.createElement('div'),name=document.createElement('div'),meta=document.createElement('div'),time=document.createElement('div'),view=document.createElement('button');card.className='task-card';spin.className='task-spin';info.className='task-info';name.className='task-name';name.textContent=wfName;meta.className='task-meta';meta.setAttribute('aria-live','polite');time.className='task-time';time.textContent='00:00';view.className='task-view';view.type='button';view.textContent='查看结果';view.hidden=true;info.append(name,meta);card.append(spin,info,time,view);list.prepend(card);const t={card,timeEl:time,metaEl:meta,spinEl:spin,viewEl:view,timer:null,startTs:Date.now(),wfName,pollFailures:0};tasks.set(jobId,t);t.timer=setInterval(()=>{t.timeEl.textContent=fmtTime((Date.now()-t.startTs)/1000)},500);refreshTaskCount();return t}
function removeTaskCard(jobId){const t=tasks.get(jobId);if(!t)return;if(t.timer)clearInterval(t.timer);t.card.remove();tasks.delete(jobId);refreshTaskCount()}
function renderTaskResult(j){registerGalleryJob(j)}
async function pollTask(jobId){const t=tasks.get(jobId);if(!t)return;try{const j=await api('/api/job/'+jobId);if(!tasks.has(jobId))return;t.pollFailures=0;t.metaEl.textContent=taskStatusText(j)+' · '+videoCoinText(j);t.spinEl.className='task-spin '+taskStatusClass(j);if(j.status==='done'){if(t.timer){clearInterval(t.timer);t.timer=null}t.timeEl.textContent=fmtTime(j.elapsed||0);renderTaskResult(j);t.viewEl.hidden=!(j.images&&j.images.length);t.viewEl.onclick=()=>{registerGalleryJob(j);document.getElementById('mediaGallery').scrollIntoView({block:'nearest'})};return}if(j.status==='error'){if(t.timer){clearInterval(t.timer);t.timer=null}t.timeEl.textContent='—';t.metaEl.textContent='✗ '+(j.error||'生成失败');return}setTimeout(()=>pollTask(jobId),5000)}catch(error){if(!tasks.has(jobId))return;t.pollFailures++;if(t.pollFailures>=6){if(t.timer){clearInterval(t.timer);t.timer=null}t.spinEl.className='task-spin err';t.timeEl.textContent='—';t.metaEl.textContent='暂时无法获取状态，刷新页面可恢复';return}t.metaEl.textContent='状态连接中断，正在重试 '+t.pollFailures+'/6';setTimeout(()=>pollTask(jobId),Math.min(12000,4000+t.pollFailures*1500))}}
async function generate(){if(genRunning)return;if(!cur)return;const workflow=cur,state=ensureMediaState(workflow.id);genRunning=true;const btn=document.getElementById('genBtn');btn.disabled=true;const st=document.getElementById('genStatus');st.textContent='正在提交…';document.getElementById('genResult').innerHTML='';let pending={};try{pending=JSON.parse(localStorage.getItem(pendingVideoSubmitKey)||'{}')}catch{}const client_request_id=pending.workflow===workflow.id&&pending.id?pending.id:'video-'+Date.now()+'-'+Math.random().toString(36).slice(2);localStorage.setItem(pendingVideoSubmitKey,JSON.stringify({workflow:workflow.id,id:client_request_id}));try{const prompt=(document.getElementById('param_prompt')?.value||'').trim();if(!prompt)throw new Error('提示词不能为空');const required=Object.entries(workflow.rh_media||{}).filter(([,m])=>m.required).map(([k])=>k);const missing=required.filter(k=>!state.tokens[k]);if(missing.length)throw new Error('缺少必传素材：'+missing.join(', '));const body={workflow:workflow.id,prompt:prompt,negative_prompt:(document.getElementById('param_negative')?.value||'').trim(),media:{...state.tokens},params:collectParams(),client_request_id};const r=await api('/api/video-generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});localStorage.removeItem(pendingVideoSubmitKey);if(!r.job_id)throw new Error(r.error||'提交失败');addTaskCard(r.job_id,workflow.name);st.textContent='✓ 已提交，任务 '+r.job_id+' 在下方队列中';pollTask(r.job_id)}catch(e){const definitiveRejection=e.status>=400&&e.status<500;if(definitiveRejection)localStorage.removeItem(pendingVideoSubmitKey);st.textContent='✗ '+e.message+(definitiveRejection?'':'；网络不明时再次点击会复用请求号')}finally{genRunning=false;btn.disabled=false}}
async function history(){const l=document.getElementById('histList');l.textContent='加载中…';const a=await api('/api/jobs?scope=video');l.replaceChildren();a.filter(j=>j.workflow&&WFS.find(w=>w.id===j.workflow)).slice(0,10).forEach(j=>{const w=WFS.find(x=>x.id===j.workflow),d=document.createElement('div'),title=document.createElement('b'),note=document.createElement('div'),button=document.createElement('button');d.className='job';title.textContent=w?w.name:'视频';note.className='note';note.textContent=j.status+' · '+videoCoinText(j)+' · '+(j.elapsed||'')+'秒';button.className='dl';button.textContent='查看结果';button.onclick=()=>{addResult(j);histOverlay.classList.remove('open')};d.append(title,note,button);l.appendChild(d)})}
async function favorites(){const l=document.getElementById('favList');l.textContent='加载中…';const a=await api('/api/favorites');l.replaceChildren();a.filter(f=>f.style_id==='video').forEach(f=>{const d=document.createElement('div');d.className='job';const promptNode=document.createElement('div');promptNode.className='note';promptNode.textContent=(f.prompt||'').slice(0,120);const isVideo=String(f.favorite_media_type||'').startsWith('video/'),media=document.createElement(isVideo?'video':'img');media.src=f.image_url;if(isVideo)media.controls=true;const link=document.createElement('a');link.className='dl';link.href=f.image_url;link.target='_blank';link.rel='noopener noreferrer';link.textContent='⬇ 下载';d.append(promptNode,media,link);l.appendChild(d)})}
document.getElementById('genBtn').onclick=generate;document.getElementById('galleryPrev').onclick=()=>selectGalleryItem(galleryIndex-1);document.getElementById('galleryNext').onclick=()=>selectGalleryItem(galleryIndex+1);document.getElementById('histOpen').onclick=()=>{histOverlay.classList.add('open');history()};document.getElementById('favOpen').onclick=()=>{favOverlay.classList.add('open');favorites()};document.querySelectorAll('.overlay .close').forEach(b=>b.onclick=()=>b.closest('.overlay').classList.remove('open'));init().then(()=>recoverTasks());
